# Generated by Django 2.2 on 2019-05-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnoverZNQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='factory_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='厂家'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='名称'),
        ),
    ]
