# Generated by Django 2.2 on 2019-05-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('user_pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('reg_time', models.DateTimeField(auto_now=True, verbose_name='注册时间')),
            ],
        ),
    ]
